### ISSUE TITLE
No console.log

### ISSUE THREAD

**Issue by NicoJuicy** [pladaria/degiro#1]
I'm running the following script:

    const DeGiro = require('degiro');

    const degiro = DeGiro.create(
        {username: 'userName', password: 'pwd'
    });

    degiro.login().then(() => degiro.searchProduct({
        text: 'GOOG'
    }))
    .then(console.log);
    degiro.getCashFunds().then(console.log);

I have node 6.5.0

Yet, when i execute it. I have no results in the console command (running on Windows, but never had any real problems with nodejs vs windows).

I don't receive an error.

Any advice?

**Comment by pladaria** [comment]
Hi, 

Your code has a bug, the `login` function is asynchronous and you are calling `getCashFunds` synchronously.

Do you have any problems running the demos from the repo?
