### ISSUE TITLE
401 Unauthorized when executing buy  

### ISSUE THREAD

**Issue by johannespetrat** [pladaria/degiro#15]
Hi, 
first of all thanks a lot for creating this library! 
Yesterday I gave it a first try and encountered an issue with executing buy orders. I provided my credentials as environment variables and then I run this command:

`degiro.login().then(() => {
    degiro.buy({
        orderType: DeGiro.OrderTypes.limited,
        productSymbol: 'ALV',
        productType: DeGiro.ProductTypes.shares,
        timeType: DeGiro.TimeTypes.day,
        size: 1,
        price: 150,
    })
    .then(console.log)
    .catch(console.error);
});`

It looks like there is a problem with the authorization because the response I get contains:

`  status: 401,
  statusText: 'Unauthorized',
  headers: 
   Headers {
     _headers: 
      { date: [Array],
        'content-type': [Array],
        'content-length': [Array],
        connection: [Array],
        'strict-transport-security': [Array],
        'content-language': [Array],
        'cache-control': [Array],
        pragma: [Array],
        expires: [Array],
        'x-zen-fury': [Array],
        server: [Array] } },
  ok: false,
  body: 
   PassThrough {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 1061,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _events: { end: [Object], prefinish: [Function: prefinish] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _transformState: 
      { afterTransform: [Function: bound afterTransform],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }`

This then results in the following error:
`TypeError: Cannot read property 'json' of undefined
    at fetch.then.then.res (/Users/Johannes/Documents/projects/quanttrading/node_modules/degiro/src/index.js:274:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

**Comment by Drag0s** [comment]
Hello @johannespetrat, 

This issue is a duplicated of issue #13.
This issue and other bugs are fixed in the Pull Request #14 I made 2 days ago.

Seems like there is also another Pull Request without review for 10 days and the author's last commit is 15 days ago, so If you're in a hurry and you need it right now, you can use [my forked repository](https://github.com/Drag0s/degiro) with `npm install drag0s/degiro --save` or fork your own version while it's pending acceptance.

Greetings!

**Comment by johannespetrat** [comment]
thanks a lot! I can confirm it works now.
