### ISSUE TITLE
Question: What is the back-end of this API? Docs?

### ISSUE THREAD

**Issue by MatthiasKauer** [pladaria/degiro#25]
Hi,
I'm looking for brokers with trading API. With your project, degiro looks quite promising.

I am now wondering about the internals of your API:
- Are you communicating via sockets, REST, FIX? 
- What is the security model?
- Are there official API docs that you are implementing? Or did you have to reverse engineer everything?

Best regards,
Matthias

**Comment by pladaria** [comment]
Hi,
* This api client uses regular HTTPS requests
* Security model: same security as HTTPS
* There is no official documentation nor a public API so everything is reverse engineered from their web client

**Comment by MatthiasKauer** [comment]
Thank you for the clarification.
So you are effectively behaving like a browser calling the REST endpoints, right?
