### ISSUE TITLE
UnhandledPromiseRejectionWarning - Login Error

### ISSUE THREAD

**Issue by dooleyb1** [pladaria/degiro#26]
I'm encountering an error when I try to login to my DeGiro account via the provided API. It was working previously for me a few days ago however after changing a few things around it seems to no longer work. I have researched around for solutions to the error and have yet to find anything to resolve the issue. 

**Error:**
`(node:3578) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Login error
(node:3578) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Code being executed:**
```
const username = process.env.DEGIRO_USERNAME;
const pass = process.env.DEGIRO_PASS;
const DeGiro = require('degiro');

const degiro = DeGiro.create({username: username, password: pass});
degiro.login().then(session => console.log(session));
```

I am relatively new to both Node.js and JavaScript. Any help is much appreciated, and thanks for your hard work on the API, seems brilliant so far!

**Comment by dooleyb1** [comment]
**RESOLVED**

Fixed issue using [dotenv](https://github.com/motdotla/dotenv).

**Comment by snakeyak** [comment]
hi @dooleyb1 , could you please elaborate on how you fixed it? Having the same issue, not sure how to fix it with dotenv. Thanks

**Comment by dooleyb1** [comment]
Hey @snakeyak, 

First I installed dotenv,
`npm install dotenv --save`

Then I required dotenv as part of my .js program,
`require('dotenv').config()
dotenv.load();`

Following this you then create a new document and save it as '.env'. In this write the environment variables you would like to pass to the program e.g
`DEGIRO_USERNAME=dooleyb1
DEGIRO_PASSWORD=123456`

Then, within your program read and define the environment variables as local constants within your program as follows:
`const username = process.env.DEGIRO_USERNAME;
const pass = process.env.DEGIRO_PASSWORD;`

Then, as per @pladaria's defined API
`const DeGiro = require('degiro');

const degiro = DeGiro.create({username: username, password: pass});

degiro.login()
.then(console.log)
    .catch(console.error);`

Hope this helps!

**Comment by snakeyak** [comment]
Thank you @dooleyb1

**Comment by pladaria** [comment]
Alternatively you can simply execute your program like:

    DEGIRO_USERNAME=user DEGIRO_PASSWORD=pass node myprogram.js

This should work for all unix-like environments (no idea about windows)
