### ISSUE TITLE
Error: only absolute urls are supported

### ISSUE THREAD

**Issue by sunkaflek** [pladaria/degiro#27]
When I reuse the session, I get `Error: only absolute urls are supported` from `node-fetch` module.
Apparently the URL it gets is `nullv5/update/ ....` , without the domain.

My code:
```
router.post('/', function(req, res, next) {

  const DeGiro = require('degiro');
  const degiro = DeGiro.create({sessionId: req.body.session.id, account: req.body.session.account})

	degiro.getPortfolio()
	.then(console.log)
	.catch(console.error)

});
```
Am I doing something wrong? Thank you

**Comment by pladaria** [comment]
Thanks for reporting... and sorry for the delay

There was a bug in the code and some missing documentation. I've released a new library version (v.3.0.1) which includes son breaking change (please check release notes)
