### ISSUE TITLE
trading not working anymore

### ISSUE THREAD

**Issue by christophglawe** [pladaria/degiro#29]
Hi,
I am using the API on a daily basis. Since a few days I get an error when I try to trade:
`Error: errors.field.invalid.format
    at Error (native)
    at checkSuccess (PATHTOSCRIPT/node_modules/degiro/src/index.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)`
Did DeGiro change something recently ? 

The error occurs also in simplified code example (which is essentially the buy.js file from examples):

const DeGiro = require('degiro');
const degiro = DeGiro.create({username: MYUSERNAME, password: MYPASSWORD});
degiro.login().then(() =>
    degiro.setOrder({
        buysell: DeGiro.Actions.buy,
        orderType: DeGiro.OrderTypes.limited,
        productId: '8066561', // Google
        timeType: DeGiro.TimeTypes.permanent,
        size: 1,
        price: 1300,
    })
        .then(console.log)
        .catch(console.error));

Somebody having the same problem or an idea how to solve the issue? 

Greetings
Christoph

**Comment by onofff** [comment]
Hi, 
Same issue here., no idea how to solve it.
searchProduct() however is still working as expected.

Greetings 
Pedro

**Comment by d99kris** [comment]
You can try apply the patch I posted above, or just clone my (temporary) fork https://github.com/d99kris/degiro until the main repository is updated. Note however that your application need to change from setting "buysell" to "buySell" (i.e. upper case S) to use this version.

**Comment by onofff** [comment]
Perfect. Worked like a charm.
Thank you.

**Comment by christophglawe** [comment]
Thanks d99kris. Fork works for me too.

**Comment by onofff** [comment]
Hi,
I am facing the same issue again since saturday, i was using the fix by d99Kris.
Anyone else with same issue? Did Degiro change it again?

**Comment by christophglawe** [comment]
d99Kris fork is still working for me . 
Did it work for you in the meantime ? 
The error message looks similar to the first one .
For me it seems you have installed the degiro api globally on your system (from your path). 
Where did you install  the fork by d99Kris ? Maybe your Skript is trying to access the original api installation , bot the fork ?

**Comment by d99kris** [comment]
FYI @onofff the fix is still working for me as well, as of today. Unfortunately I don't have much troubleshooting ideas to add to @christophglawe's ideas. 

A very general approach - which I used to create my fix - is to try placing a manual order on Degiro using Chrome with Developer Tools enabled, and watch Network tab when clicking "Confirm". A new row should be added, right-click on that and select "Copy as curl". Paste it into a text editor and check the data/json part. See if the parameters matches what this node project sends.

**Comment by onofff** [comment]
Hi, thank you both for the help... i can't understand why but after rebooting the server it start working again, with the same code...

**Comment by svolder** [comment]
Txs d99kris, your advice with crome made all the difference!
'{"buySell":"BUY","orderType":0,"productId":"1177300","timeType":1,"price":4.53,"size":100}' --compressed
