### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by emmerink** [pladaria/degiro#32]
I am trying to login like this:

```
const DeGiro = require('degiro');

const degiro = DeGiro.create({username: 'johndoe', password: 'example'});

degiro.login()
    .then(console.log)
    .catch(console.error);
```

It fires an OPTIONS request to https://trader.degiro.nl/login/secure/login
which results in a 500 Internal Server Error

If I look at the web client at trader.degiro.nl I see a
[POST] https://trader.degiro.nl/login/secure/login instead

**Comment by pladaria** [comment]
Looks like you are trying to execute that code in a browser. Don't do that. Use node.js
