### ISSUE TITLE
searchProduct example not working

### ISSUE THREAD

**Issue by cbarbu** [pladaria/degiro#35]
Hi and thanks for your work, 
There is a syntax error when I try to launch this example : 

> 
> node search-product.js 
> /home/cbarbu/Documents/perso/finances/node_modules/degiro/examples/search-product.js:3
> (async () => {
>        ^
> 
> SyntaxError: Unexpected token (
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.runMain (module.js:611:10)
>     at run (bootstrap_node.js:387:7)
>     at startup (bootstrap_node.js:153:9)

**Comment by cbarbu** [comment]
Note : this still doesn't work.

**Comment by pladaria** [comment]
This is a syntax error, not an error with the API
Are you using a modern node.js? Try one with async/await support
