### ISSUE TITLE
Important: DeGiro is not allowing this, better use Interactive Brokers

### ISSUE THREAD

**Issue by jodler303** [pladaria/degiro#48]
Important to know, DeGiro is not allowing this type of usage. Their argumentation is that they don't have a license that allows (semi-)automated trading. Everything that is beyond manually clicking their website is considered to be automated trading.

If they find out you are using "automated order placement" they will first warn you and then possibly block your account. 

I have not been blocked yet, but have received a warning. I have not even used a bot or so, just macros so i can be much faster for order placement than with their website. I will close my account because DeGiro becomes useless for me, their web tool is rather lame and their live price updates seem to be delayed approx. 3 seconds, at least compared with tradingview.com.

By the definition of DeGiro, any usage that is not clicking their web trading tool is classified as "automated trading".

Just letting you guys know what to expect ...   i've wasted quite some hours to develop my own trading tool and now i have to re-implement everything for another API. What a waste of time ...

**Comment by jodler303** [comment]
p.s. i am in no way affiliated with Interactive Brokers. IB are my choice because they offer a Linux trading environment ...

**Comment by pladaria** [comment]
Well, you could also automate trading clicking their site using puppeteer or selenium... 

Anyway, what you comment is not an issue of this library, there's nothing we can do to fix that.

**Comment by franky303** [comment]
While your response is valid, it would be fair to point out it's not allowed by DeGiro business terms in the readme. People like me are spending hours to implement something, just to find out it's not allowed by DeGiro's business terms as soon as it's working. That's my point.

**Comment by icastillejogomez** [comment]
Please, visit https://github.com/icastillejogomez/degiro-api and we can go on with this project
