### ISSUE TITLE
Placing buying order

### ISSUE THREAD

**Issue by josepDeltrading** [pladaria/degiro#53]
Hi,

I have no knowledge in Java, but im developing code in Python. I was wondering after having downloaded your code in Visual Studio Code, which piece of code would let me log in and place a market order?

I have struggle with "Cannot find runtime 'node' on PATH. Is 'node installed?" when I try to run the example of Buy.js

Thank you!

**Comment by pladaria** [comment]
Did you install node.js?

There's an examples folder, try to run them
