### ISSUE TITLE
Not working from today

### ISSUE THREAD

**Issue by oscarmoutinho** [pladaria/degiro#54]
Not working from today.
It seams DEGIRO had modify messages.

**Comment by alexpilk** [comment]
Looks like they changed the structure of their login response. 

`{ id: <session id>,
  account: undefined,
  userToken: undefined,
  clientInfo: 
   { data: 
      { id: <id>,
        intAccount: <intAccount>, ...
 } } }
`

Quick fix that worked is overwriting session.account with intAccount from the login response:
`session.account = session.clientInfo.data.intAccount;`

**Comment by alexpilk** [comment]
Submitted pull request: https://github.com/pladaria/degiro/pull/55

**Comment by pladaria** [comment]
Thanks, will review that this afternoon

**Comment by oscarmoutinho** [comment]
Old:
...session.account
Now:
...session.clientInfo.data.intAccount

**Comment by oscarmoutinho** [comment]
Forget my last message. It was my patch (I'll update the module as soon as last version go live).

**Comment by pladaria** [comment]
PR merged. Thanks for contributing!

Please let me know if you find any other issues :)
