### ISSUE TITLE
Search product error

### ISSUE THREAD

**Issue by Caradouche** [pladaria/degiro#6]
Hi,

The search product function doesn't work anymore, they added a "s" after product

return fetch(`${BASE_URL}/product_search/secure/v4/product/lookup?intAccount=${session.account}&sessionId=${session.id}&${params}`)

return fetch(`${BASE_URL}/product_search/secure/v4/products/lookup?intAccount=${session.account}&sessionId=${session.id}&${params}`)

**Comment by pladaria** [comment]
fixed in v1.0.2
