### ISSUE TITLE
Get Portfolio not working anymore

### ISSUE THREAD

**Issue by lwieseke** [pladaria/degiro#9]
Getting Portfolio leads to a page telling me :
HTTP Status 401 - Unauthorized AuthenticationCredentialsNotFoundException

{ FetchError: invalid json response body at https://trader.degiro.nl/trading/secure/v5/update/31022419;jsessionid=C63EFB5C8094CB249592460D7FEF390A.staging1?portfolio=0 reason: Unexpected token < in JSON at position 0
    at C:\Private Projects\autotrader\node_modules\node-fetch\lib\body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'FetchError',
  message: 'invalid json response body at https://trader.degiro.nl/trading/secure/v5/update/31022419;jsessionid=C63EFB5C8094CB249592460D7FEF390A.staging1?portfolio=0 reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

**Comment by Sire** [comment]
solution in #8 ;)

**Comment by lwieseke** [comment]
Thanks for the quick fix !

**Comment by pladaria** [comment]
Closing. Please if you continue having problems, reopen the ticket and I will investigate
